package dev.sieve.core.geo;

import java.util.Map;

/**
 * Country spellings seen on sanctions lists that the JDK's country names do not cover: official
 * long forms, inverted forms, former names and nationality adjectives.
 */
final class CountryAliases {

    static final Map<String, String> ALIASES =
            Map.ofEntries(
                    // Official long forms and inverted forms
                    Map.entry("Russian Federation", "RU"),
                    Map.entry("Fédération de Russie", "RU"),
                    Map.entry("Russische Föderation", "RU"),
                    Map.entry("Iran, Islamic Republic of", "IR"),
                    Map.entry("Islamic Republic of Iran", "IR"),
                    Map.entry("Syrian Arab Republic", "SY"),
                    Map.entry("North Korea", "KP"),
                    Map.entry("Korea, North", "KP"),
                    Map.entry("Korea, Democratic People's Republic of", "KP"),
                    Map.entry("Democratic People's Republic of Korea", "KP"),
                    Map.entry("DPRK", "KP"),
                    Map.entry("DPR Korea", "KP"),
                    Map.entry("South Korea", "KR"),
                    Map.entry("Korea, South", "KR"),
                    Map.entry("Korea, Republic of", "KR"),
                    Map.entry("Republic of Korea", "KR"),
                    Map.entry("Burma", "MM"),
                    Map.entry("Myanmar", "MM"),
                    Map.entry("Ivory Coast", "CI"),
                    Map.entry("Democratic Republic of the Congo", "CD"),
                    Map.entry("Congo, Democratic Republic of the", "CD"),
                    Map.entry("Congo, The Democratic Republic of the", "CD"),
                    Map.entry("DR Congo", "CD"),
                    Map.entry("DRC", "CD"),
                    Map.entry("Zaire", "CD"),
                    Map.entry("Republic of the Congo", "CG"),
                    Map.entry("Congo, Republic of the", "CG"),
                    Map.entry("Congo", "CG"),
                    Map.entry("Palestine", "PS"),
                    Map.entry("State of Palestine", "PS"),
                    Map.entry("Palestinian Territories", "PS"),
                    Map.entry("Palestinian Territory, Occupied", "PS"),
                    Map.entry("Occupied Palestinian Territory", "PS"),
                    Map.entry("West Bank", "PS"),
                    Map.entry("Gaza", "PS"),
                    Map.entry("Gaza Strip", "PS"),
                    Map.entry("Kosovo", CountryNormalizer.KOSOVO),
                    Map.entry("Laos", "LA"),
                    Map.entry("Lao People's Democratic Republic", "LA"),
                    Map.entry("Viet Nam", "VN"),
                    Map.entry("Venezuela, Bolivarian Republic of", "VE"),
                    Map.entry("Bolivarian Republic of Venezuela", "VE"),
                    Map.entry("Bolivia, Plurinational State of", "BO"),
                    Map.entry("Tanzania, United Republic of", "TZ"),
                    Map.entry("United Republic of Tanzania", "TZ"),
                    Map.entry("Moldova, Republic of", "MD"),
                    Map.entry("Republic of Moldova", "MD"),
                    Map.entry("Macedonia", "MK"),
                    Map.entry("North Macedonia", "MK"),
                    Map.entry("Former Yugoslav Republic of Macedonia", "MK"),
                    Map.entry("Czech Republic", "CZ"),
                    Map.entry("Turkey", "TR"),
                    Map.entry("Turkiye", "TR"),
                    Map.entry("Republic of Turkiye", "TR"),
                    Map.entry("United States of America", "US"),
                    Map.entry("USA", "US"),
                    Map.entry("U.S.A.", "US"),
                    Map.entry("United Kingdom of Great Britain and Northern Ireland", "GB"),
                    Map.entry("Great Britain", "GB"),
                    Map.entry("UK", "GB"),
                    Map.entry("England", "GB"),
                    Map.entry("UAE", "AE"),
                    Map.entry("Libyan Arab Jamahiriya", "LY"),
                    Map.entry("Crimea", "UA"),
                    Map.entry("Hong Kong", "HK"),
                    Map.entry("Virgin Islands, British", "VG"),
                    Map.entry("Virgin Islands, U.S.", "VI"),
                    Map.entry("Macau", "MO"),
                    Map.entry("Macao", "MO"),
                    Map.entry("Taiwan", "TW"),
                    Map.entry("Taiwan, Province of China", "TW"),
                    Map.entry("East Timor", "TL"),
                    Map.entry("Cape Verde", "CV"),
                    Map.entry("Swaziland", "SZ"),
                    Map.entry("Holy See", "VA"),
                    Map.entry("Vatican", "VA"),
                    Map.entry("Micronesia, Federated States of", "FM"),
                    Map.entry("Brunei Darussalam", "BN"),
                    Map.entry("EL", "GR"),
                    // Official long forms in the languages of the French and Turkish lists
                    Map.entry("République démocratique du Congo", "CD"),
                    Map.entry("République du Congo", "CG"),
                    Map.entry("République populaire démocratique de Corée", "KP"),
                    Map.entry("République de Corée", "KR"),
                    Map.entry("République islamique d'Iran", "IR"),
                    Map.entry("République arabe syrienne", "SY"),
                    Map.entry("Territoires palestiniens occupés", "PS"),
                    Map.entry("Türkiye Cumhuriyeti", "TR"),
                    Map.entry("Kore Demokratik Halk Cumhuriyeti", "KP"),
                    Map.entry("Kongo Demokratik Cumhuriyeti", "CD"),
                    Map.entry("İran İslam Cumhuriyeti", "IR"),
                    Map.entry("Suriye Arap Cumhuriyeti", "SY"),
                    Map.entry("Rusya Federasyonu", "RU"),
                    Map.entry("Filistin", "PS"),
                    Map.entry("RPDC", "KP"),
                    Map.entry("RDC", "CD"),
                    Map.entry("Centrafrique", "CF"),
                    Map.entry("État de Palestine", "PS"),
                    Map.entry("États-Unis d'Amérique", "US"),
                    Map.entry("ABD", "US"),
                    Map.entry("Avusturya", "AT"),
                    Map.entry("Avustrya", "AT"),
                    Map.entry("İngiltere", "GB"),
                    Map.entry("República Bolivariana de Venezuela", "VE"),
                    Map.entry("Venezuela, República Bolivariana de", "VE"),
                    // Other official long forms, inverted forms and short names
                    Map.entry("Occupied Palestinian Territories", "PS"),
                    Map.entry("Palestinian Authority", "PS"),
                    Map.entry("Palestinian Territory", "PS"),
                    Map.entry("Republic of Ireland", "IE"),
                    Map.entry("North Gaza", "PS"),
                    Map.entry("Northern Gaza", "PS"),
                    Map.entry("Northern Mali", "ML"),
                    Map.entry("Republic of North Macedonia", "MK"),
                    Map.entry("North Macedonia, Republic of", "MK"),
                    Map.entry("Bosnia and Herzegowina", "BA"),
                    Map.entry("Kyrgyz Republic", "KG"),
                    Map.entry("Slovak Republic", "SK"),
                    Map.entry("Republic of Serbia", "RS"),
                    Map.entry("Egypt, Arab Republic of", "EG"),
                    Map.entry("Somalia, Federal Republic of", "SO"),
                    Map.entry("Isle of Man", "IM"),
                    Map.entry("Man, Isle of", "IM"),
                    Map.entry("Congo, People's Republic of", "CG"),
                    Map.entry("Hong Kong SAR", "HK"),
                    Map.entry("China, Hong Kong Special Administrative Region", "HK"),
                    Map.entry("PRC", "CN"),
                    Map.entry("Britain", "GB"),
                    Map.entry("RF", "RU"),
                    // Nationality adjectives
                    Map.entry("Russian", "RU"),
                    Map.entry("Iranian", "IR"),
                    Map.entry("Syrian", "SY"),
                    Map.entry("Iraqi", "IQ"),
                    Map.entry("Afghan", "AF"),
                    Map.entry("North Korean", "KP"),
                    Map.entry("South Korean", "KR"),
                    Map.entry("Chinese", "CN"),
                    Map.entry("Ukrainian", "UA"),
                    Map.entry("Belarusian", "BY"),
                    Map.entry("Belarussian", "BY"),
                    Map.entry("Venezuelan", "VE"),
                    Map.entry("Cuban", "CU"),
                    Map.entry("Lebanese", "LB"),
                    Map.entry("Yemeni", "YE"),
                    Map.entry("Libyan", "LY"),
                    Map.entry("Sudanese", "SD"),
                    Map.entry("South Sudanese", "SS"),
                    Map.entry("Somali", "SO"),
                    Map.entry("Pakistani", "PK"),
                    Map.entry("Saudi", "SA"),
                    Map.entry("Saudi Arabian", "SA"),
                    Map.entry("Emirati", "AE"),
                    Map.entry("Turkish", "TR"),
                    Map.entry("British", "GB"),
                    Map.entry("American", "US"),
                    Map.entry("German", "DE"),
                    Map.entry("French", "FR"),
                    Map.entry("Italian", "IT"),
                    Map.entry("Spanish", "ES"),
                    Map.entry("Indian", "IN"),
                    Map.entry("Egyptian", "EG"),
                    Map.entry("Jordanian", "JO"),
                    Map.entry("Kuwaiti", "KW"),
                    Map.entry("Qatari", "QA"),
                    Map.entry("Bahraini", "BH"),
                    Map.entry("Omani", "OM"),
                    Map.entry("Palestinian", "PS"),
                    Map.entry("Israeli", "IL"),
                    Map.entry("Nigerian", "NG"),
                    Map.entry("Malian", "ML"),
                    Map.entry("Burmese", "MM"),
                    Map.entry("Cypriot", "CY"),
                    Map.entry("Georgian", "GE"),
                    Map.entry("Armenian", "AM"),
                    Map.entry("Azerbaijani", "AZ"),
                    Map.entry("Kazakh", "KZ"),
                    Map.entry("Kazakhstani", "KZ"),
                    Map.entry("Uzbek", "UZ"),
                    Map.entry("Tajik", "TJ"),
                    Map.entry("Kyrgyz", "KG"),
                    Map.entry("Turkmen", "TM"),
                    Map.entry("Mexican", "MX"),
                    Map.entry("Colombian", "CO"),
                    Map.entry("Nicaraguan", "NI"),
                    Map.entry("Eritrean", "ER"),
                    Map.entry("Ethiopian", "ET"),
                    Map.entry("Kenyan", "KE"),
                    Map.entry("Tunisian", "TN"),
                    Map.entry("Algerian", "DZ"),
                    Map.entry("Moroccan", "MA"),
                    Map.entry("Mauritanian", "MR"),
                    Map.entry("Bosnian", "BA"),
                    Map.entry("Serbian", "RS"),
                    Map.entry("Montenegrin", "ME"),
                    Map.entry("Croatian", "HR"),
                    Map.entry("Albanian", "AL"),
                    Map.entry("Kosovar", CountryNormalizer.KOSOVO),
                    Map.entry("Moldovan", "MD"),
                    Map.entry("Latvian", "LV"),
                    Map.entry("Lithuanian", "LT"),
                    Map.entry("Estonian", "EE"),
                    Map.entry("Polish", "PL"),
                    Map.entry("Belgian", "BE"),
                    Map.entry("Dutch", "NL"),
                    Map.entry("Swiss", "CH"),
                    Map.entry("Austrian", "AT"),
                    Map.entry("Canadian", "CA"),
                    Map.entry("Australian", "AU"),
                    Map.entry("Japanese", "JP"),
                    Map.entry("Indonesian", "ID"),
                    Map.entry("Filipino", "PH"),
                    Map.entry("Malaysian", "MY"),
                    Map.entry("Thai", "TH"),
                    Map.entry("Vietnamese", "VN"),
                    Map.entry("Cambodian", "KH"),
                    Map.entry("Bangladeshi", "BD"),
                    Map.entry("Sri Lankan", "LK"),
                    Map.entry("Nepali", "NP"),
                    Map.entry("Zimbabwean", "ZW"),
                    Map.entry("South African", "ZA"),
                    Map.entry("Central African", "CF"),
                    Map.entry("Chadian", "TD"),
                    Map.entry("Burkinabe", "BF"),
                    Map.entry("Haitian", "HT"),
                    Map.entry("Panamanian", "PA"),
                    Map.entry("Salvadoran", "SV"),
                    Map.entry("Honduran", "HN"),
                    Map.entry("Guatemalan", "GT"),
                    Map.entry("Dominican", "DO"),
                    Map.entry("Ecuadoran", "EC"),
                    Map.entry("Ecuadorian", "EC"),
                    Map.entry("Brazilian", "BR"),
                    Map.entry("Argentinian", "AR"),
                    Map.entry("Argentine", "AR"),
                    Map.entry("Jamaican", "JM"),
                    Map.entry("Hungarian", "HU"),
                    Map.entry("Swedish", "SE"),
                    Map.entry("Danish", "DK"),
                    Map.entry("Finnish", "FI"),
                    Map.entry("Bulgarian", "BG"),
                    Map.entry("Romanian", "RO"),
                    Map.entry("Czech", "CZ"),
                    Map.entry("Slovak", "SK"),
                    Map.entry("Slovene", "SI"),
                    Map.entry("Slovenian", "SI"),
                    Map.entry("Luxembourger", "LU"),
                    Map.entry("Ghanaian", "GH"),
                    Map.entry("Seychellois", "SC"),
                    Map.entry("Singaporean", "SG"),
                    Map.entry("Laotian", "LA"),
                    Map.entry("Herzegovinian", "BA"),
                    Map.entry("Ukranian", "UA"),
                    Map.entry("Irani", "IR"),
                    Map.entry("Iraní", "IR"),
                    Map.entry("Libanés", "LB"),
                    Map.entry("Libanesa", "LB"),
                    Map.entry("Israélienne", "IL"),
                    Map.entry("Palestina", "PS"),
                    // Arabic and Hebrew spellings from the Israeli and Qatari lists
                    Map.entry("يمني", "YE"),
                    Map.entry("أفغاني", "AF"),
                    Map.entry("قطري", "QA"),
                    Map.entry("لبناني", "LB"),
                    Map.entry("مصري", "EG"),
                    Map.entry("إيراني", "IR"),
                    Map.entry("سعودي", "SA"),
                    Map.entry("أردني", "JO"),
                    Map.entry("سوري", "SY"),
                    Map.entry("אזרחות פלסטינית", "PS"),
                    Map.entry("הרשות הפלסטינית", "PS"),
                    Map.entry("אירן", "IR"),
                    Map.entry("עירק", "IQ"),
                    Map.entry("פיליפינים", "PH"),
                    Map.entry("פיליפים", "PH"),
                    Map.entry("אפגניסטן", "AF"),
                    Map.entry("טרינידד וטובאגו", "TT"),
                    Map.entry("מאלזיה", "MY"),
                    Map.entry("סעודיה", "SA"),
                    Map.entry("תורכיה", "TR"));

    private CountryAliases() {}
}
